### ISSUE TITLE
nodemailer-fetch non catchable errors

### ISSUE THREAD

**Issue by simllll** [nodemailer/nodemailer-fetch#1]
Sending an email with an attachment (http url with a 404 return code), creates an uncatchable exception:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Invalid status code 404
    at ClientRequest.<anonymous> (d:\users\stretter\workspaceNodejs\hokify-server\node_modules\nodemailer\node_modules\nodemailer-fetch\lib\fetch.js:146:36)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
a try / catch block or anything else I've tried does not catch this error.

tested with latest Nodemailer 2.4.0.
Running Node JS 4.4.x
happening on OS Windows & Linux

Simple test code:

```
var nodemailer = require('nodemailer');
var mailTransport = require(...); // set up a mail transporter
var nodemailerTransport = nodemailer.createTransport(mailTransport(... config for mailtransporter ...));

var mailOptions = {};
mailOptions.attachments = [{
    filename: "deadlink",
    path: "http://google.com/deadlink"
}];

mailOptions.text = "test maiL";
mailOptions.to = "someone@whereisthererror.com";
mailOptions.subject = "mail subject";

try {
    nodemailerTransport.sendMail(mailOptions, function (err) {
        console.log("ERROR", err);
    });
}catch(err) {
    console.log("ERROR", err);
};
```

Anyone an idea what is happening here?

**Comment by andris9** [comment]
Could you specify which transport are you using. This error should be handled by all SMTP-based tranports

**Comment by simllll** [comment]
thanks for your hint, just handed in a PR
